---
kind: pipeline
type: ssh
name: deploy

server:
    host:
      from_secret: host
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key

clone:
    disable: true

trigger:
    branch:
      - master

steps:
    - name: deploy
      commands:
        - cd //var/gopher/envs.net
        - sudo -Hu root git pull origin master
        - sudo -Hu root chown -R gopher:root /var/gopher/envs.net/
